import Head from 'next/head'
import { useTheme } from '@/contexts/ThemeProviderContext'
import { Container, SideBarDiv, ContentDiv } from '@/styles/pages/indexStyle'
import SideBarComponent from '@/components/SideBar'
import { useState } from 'react'

const Home = () => {
    const { toggleTheme } = useTheme()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <SideBarDiv>
                    <SideBarComponent />
                </SideBarDiv>
                <ContentDiv>
                    <h1>Hello world</h1>
                    <button onClick={toggleTheme}>changeTheme</button>
                </ContentDiv>
            </Container>
        </>
    )
}

export default Home
