import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CardItem from "../components/card";
import { apiBase, apiKey } from "../lib/rawg";

export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul className={"flex gap-4 flex-wrap justify-center my-10"}>
          {list.map((item) => (
            <>
              <li key={item.slug}>
                <CardItem
                  id={item.id}
                  name={item.name}
                  background_image={item.background_image}
                  rating={item.rating}
                  tags={item.tags}
                />
              </li>
            </>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(`${apiBase}/games?key=${apiKey}&page_size=40`);
  const json = await res.json();
  return {
    props: {
      list: json.results,
    },
  };
};
