import Head from 'next/head';
import logo from '../public/GameStoreLogo.png';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import CardItem from '../components/card';
import SideBar from '../components/sidebar';
import { apiBase, apiKey } from '../lib/rawg';

export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={`${styles.navbar} flex ml-4`}>
        <div
          className={`flex justify-center gap-4 items-center min-[650px]:hidden`}
        >
          <Image src={logo} alt="Game Store Logo" width={50} height={50} />
          <h5 className={`${styles.title} text-2xl`}>Game Store</h5>
        </div>
      </div>

      <div className={`${styles.sidebar} max-[650px]:hidden`}>
        <SideBar />
      </div>

      <div className={`${styles.main} overflow-y-scroll`}>
        {/* <ul className={"flex gap-4 flex-wrap justify-center my-10"}>
          {list.map((item) => (
            <>
              <li key={item.slug}>
                <CardItem
                  id={item.id}
                  name={item.name}
                  background_image={item.background_image}
                  rating={item.rating}
                  tags={item.tags}
                />
              </li>
            </>
          ))}
        </ul> */}
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(`${apiBase}/games?key=${apiKey}&page_size=10`);
  const json = await res.json();
  return {
    props: {
      list: json.results,
    },
  };
};
