import Head from "next/head";
import styles from "../styles/Home.module.css";
import CardItem from "../components/card";
import SideBar from "../components/sidebar";
import { apiBase, apiKey } from "../lib/rawg";


export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.navbar}>

      </div>

      <div className={styles.sidebar}>
          <SideBar/>
      </div>

      <div className={`${styles.main} overflow-y-scroll`}>
        <ul className={"flex gap-4 flex-wrap justify-center my-10"}>
          {list.map((item) => (
            <>
              <li key={item.slug}>
                <CardItem
                  id={item.id}
                  name={item.name}
                  background_image={item.background_image}
                  rating={item.rating}
                  tags={item.tags}
                />
              </li>
            </>
          ))}
        </ul>
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(`${apiBase}/games?key=${apiKey}&page_size=10`);
  const json = await res.json();
  return {
    props: {
      list: json.results,
    },
  };
};
